### PR TITLE
Switch to Results, and a bunch of nightly fixes

### LINKED ISSUE #7: Consider use of Result<T,E> over Option<T> from parse output.
It's probably nice to know if and why the parse failed at some point, rather than just returning `None`.

### LINKED ISSUE #13: Breaks under nightly
The FromStr trait has changed so much that rust-email's impl breaks. This is probably a good time to fix https://github.com/niax/rust-email/issues/7 too.

### PR DESCRIPTION
**Pull request by untitaker**
This is work-in-progress. The test "test_address_list_parsing_groups"
from `src/address.rs` is also currently hanging.

Fixes #7
Fixes #13

### CODE REVIEW

**Comment by untitaker** [comment]
The test fails now properly, but I still have no idea where the issue is.

**Comment by untitaker** [comment]
The bug has been fixed with https://github.com/niax/rust-email/commit/f0b8a82ad21c86729681a41ede4ba967ed3ee830, but I wonder how the tests could've passed before.

File: src/address.rs [hunk 1]
```diff
@@ -145,125 +148,136 @@ impl<'s> AddressParser<'s> {
...
+                    // Is a group
+                    result.push(x);
+                    expected_separator = ';';
+                },
+                Err(e) => {
+                    // If we failed to parse as group, try again as mailbox
+                    self.p.pop_position();
+                    result.push(Address::Mailbox(match self.parse_mailbox() {
+                        Ok(x) => x,
+                        Err(e2) => return Err(ParsingError::new(
```
Comment (niax) [inline src/address.rs]: This is a little odd due to the way Address List parsing is handled - We don't know ahead of time if it's a group or mailbox, so it perhaps doesn't make sense to say how the group parsing errored if the thing is really a Mailbox.

This whole change is also a bit unusual as to what happens with a malformed header that contains valid addresses but  is malformed at the end - would we want to say "These things were fine, others weren't"? A kind of three-state Result - OK, OK-with-Errors or Errors. This is what was stopping me from implementing Result over Option and I still don't think there's a good answer for it.

Perhaps the right way of handling this is having ParsingError types that have a field for a partial result? I'm not sure - it needs further thought.

Comment (untitaker) [inline src/address.rs]: I'd consider partial results to be a separate feature (which I doubt is worth the implementation effort), and the use of results over options to be a strict improvement. The original reason I implemented this was because some trait from rust itself made the switch from options to results.

File: src/results.rs [hunk 2]
```diff
@@ -0,0 +1,33 @@
+use std::fmt;
+use std::error::Error;
+
+#[derive(Debug)]
+pub struct ParsingError {
+    desc: String,
```
Comment (niax) [inline src/results.rs]: Not sure how I feel about "stringly-typed" errors for parsing. At the very least there are some standard parsing error states - Expected x and got y and Unexpected EOF for example - which could be modeled as an Enum.

Comment (untitaker) [inline src/results.rs]: Totally agree. I left it that way for now because there were other things to worry about.

Comment (niax) [inline src/results.rs]: I guess it could be switched to something like:

```rust
enum ParsingError {
  Other(String)
}
```

So the intent to use an enum is clear for the future of the API

Comment (untitaker) [inline src/results.rs]: I rather thought about modelling it after old_io::IoError, have a struct with enum inside.

**Comment by untitaker** [comment]
I added a few helper functions to the base parser, I hope they're alright.

**Comment by untitaker** [comment]
Are you okay with removing all experimental tags? They don't exist anymore and I only get warnings.

File: src/rfc822.rs [hunk 3]
```diff
@@ -59,32 +60,69 @@ impl<'s> Rfc822DateParser<'s> {
     #[inline]
     fn consume_u32(&mut self) -> Option<u32> {
```
Comment (untitaker) [inline src/rfc822.rs]: Shouldn't this rewind the position if it failed to parse the word as number?

File: src/mimeheaders.rs [hunk 4]
```diff
@@ -24,36 +25,36 @@ pub struct MimeContentTypeHeader {
...
 
         if mime_parts.len() == 2 {
-            Some(MimeContentTypeHeader {
+            Ok(MimeContentTypeHeader {
                 content_type: (mime_parts[0].to_string(), mime_parts[1].to_string()),
                 params: params
             })
         } else {
-            None
+            Err(ParsingError::new("Too many mime parts.".to_string()))  // FIXME
```
Comment (untitaker) [inline src/mimeheaders.rs]: Could we just panic here, or don't do the check? If ``splitn(2, ...)`` returns more than two items, there must be something else wrong.

File: src/address.rs [hunk 5]
```diff
@@ -94,19 +95,21 @@ impl fmt::String for Mailbox {
...
-    fn from_header(value: String) -> Option<Vec<Address>> {
-        Some(AddressParser::new(value.as_slice()).parse_address_list())
+    fn from_header(value: String) -> ParsingResult<Vec<Address>> {
+        AddressParser::new(value.as_slice()).parse_address_list()
     }
 }
 
 impl ToFoldedHeader for Vec<Address> {
-    fn to_folded_header(start_pos: usize, value: Vec<Address>) -> Option<String> {
+    fn to_folded_header(start_pos: usize, value: Vec<Address>) -> ParsingResult<String> {
```
Comment (untitaker) [inline src/address.rs]: Returning a ``ParsingResult`` in APIs that don't actually parse anything is a bit ugly. Any better naming suggestions, or should we tell people to deal w/ it?

Comment (niax) [inline src/address.rs]: The intent of `to_header` and `to_folded_header` returning an Option was to allow implementors to indicate a failure to stringify their value. This could be implemented using associated types where we allow the definintion of an error type per implementation. Perhaps something like:

```rust
trait ToFoldedHeader {
    type StringifyError;
 
    fn to_folded_header(pos: usize, value: Self) -> Result<String, Self::StringifyError>;
}
 
struct Foo {
    a: usize,
}
 
impl ToFoldedHeader for Foo {
    type StringifyError = ();
 
    fn to_folded_header(pos: usize, value: Self) -> Result<String, ()> {
        return Ok(format!("{}", value.a))
    }
}
 
fn print_folded<T: ToFoldedHeader>(val: T) {
    println!("{}", ToFoldedHeader::to_folded_header(0, val).unwrap_or("FAIL!".to_string()));
}
 
fn main() {
    let a = Foo { a: 10 };
    print_folded(a);
}
``` 

This allows, like in the Foo case, for something to not have an error type (through the use of Unit) or specify their own errors.

File: src/rfc822.rs (hunk 3 above)
Comment (niax) [inline src/rfc822.rs]: `consume_*` functions have been woefully inconsistent about if they should roll back in case of failure or not - either they all should or the callees should care about the error cases.

I suspect it's right for the consume function to remember where it was to begin with if they return a Result type. It's also probably a good idea to remove the push/pop position functions on the base parser because I think maintaining this information in the stack is probably nicer than having to handle this ourselves.

File: src/mimeheaders.rs (hunk 4 above)
Comment (niax) [inline src/mimeheaders.rs]: `splitn(2, ...)` returns *at most* 2 elements - if the parsing string has no slashes, then `mime_parts` will only have one item which we shouldn't panic at, just tell the user that this couldn't be parsed.

File: src/address.rs (hunk 5 above)
Comment (niax) [inline src/address.rs]: Come to think of it, this should probably be extended to FromHeader such that parsing implementations can use their own Error types, even if all the stock impls use ParsingError

Comment (untitaker) [inline src/address.rs]: I don't think having `()` as an error type is possible, it has to implement `std::error::Error`.

Comment (untitaker) [inline src/address.rs]: Maybe we should make ParsingError a trait to implement then?

File: src/address.rs (hunk 1 above)
Comment (untitaker) [inline src/address.rs]: @niax Have you come to a decision on this (and other parts of this PR)?

**Comment by untitaker** [comment]
@niax After updating this PR for the latest nightly, it seems that Rust discourages having the tests in the same crate as the tested code. I've come to this conclusion because Rust wants me to use the ``test`` feature, yet the only place where I can do so is for the whole crate, which gives me an "unused feature" warning when compiling rust-email without tests.

File: src/address.rs (hunk 1 above)
Comment (niax) [inline src/address.rs]: As I can't think of a better idea, let's go with what we have for now and see where it takes us.

**Comment by niax** [comment]
As it builds for now, let's consider where the tests are as a separate issue.

**Comment by untitaker** [comment]
Ok, cool. Maybe I'll provide more PRs regarding the error handling. I currently don't have the motivation for that though, this PR rather resulted out of the problem that ``email`` was breaking on nightly.

**Comment by niax** [comment]
This change has been included in 0.0.9 which has been published to crates.io
